---
abstract: 'Declarative exports and simple Devel-Declare interface.'
author:
  - 'Chad Granum <exodist7@gmail.com>'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3605'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Exporter-Declare
provides:
  Exporter::Declare:
    file: lib/Exporter/Declare.pm
    version: 0.006
  Exporter::Declare::Base:
    file: lib/Exporter/Declare.pm
  Exporter::Declare::Parser:
    file: lib/Exporter/Declare/Parser.pm
  Exporter::Declare::Parser::Begin:
    file: lib/Exporter/Declare/Parser/Begin.pm
  Exporter::Declare::Parser::Codeblock:
    file: lib/Exporter/Declare/Parser/Codeblock.pm
  Exporter::Declare::Parser::Emulate:
    file: lib/Exporter/Declare/Parser/Emulate.pm
  Exporter::Declare::Parser::Export:
    file: lib/Exporter/Declare/Parser/Export.pm
  Exporter::Declare::Parser::Method:
    file: lib/Exporter/Declare/Parser/Method.pm
  Exporter::Declare::Parser::Sublike:
    file: lib/Exporter/Declare/Parser/Sublike.pm
requires:
  B::Compiling: 0.02
  B::Hooks::EndOfScope: 0.08
  Devel::Declare: 0.006
  Test::Exception::LessClever: 0
  Test::Simple: 0.88
resources:
  bugtracker: http://github.com/exodist/Exporter-Declare/issues
  license: http://dev.perl.org/licenses/
  repository: http://github.com/exodist/Exporter-Declare
version: 0.006
