---
abstract: 'Declarative exports and simple Devel-Declare interface.'
author:
  - 'Chad Granum <exodist7@gmail.com>'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Exporter-Declare
provides:
  Exporter::Declare:
    file: lib/Exporter/Declare.pm
    version: 0.020
requires:
  Carp: 0
  Devel::Declare::Parser: 0.017
  Scalar::Util: 0
  Test::Exception::LessClever: 0.005
  Test::Simple: 0.88
resources:
  bugtracker: http://github.com/exodist/Exporter-Declare/issues
  homepage: http://open-exodus.net/projects/Exporter-Declare
  license: http://dev.perl.org/licenses/
  repository: http://github.com/exodist/Exporter-Declare
version: 0.020
